pragma Singleton

import QtQuick 2.3

Item {

    //颜色设置
    //disable
    property string window_Disabled:"#222222"
    property string windowShade_Disabled:"#333333"
    property string windowShadeDark_Disabled:"#282828"
    property string text_Disabled:"#707070"
    property string warningText_Disabled:"#f85761"
    property string button_Disabled:"#707070"
    property string buttonText_Disabled:"#202020"
    property string buttonHighlight_Disabled:"#3a3a3a"
    property string buttonHighlightText_Disabled:"#2c2c2c"
    property string primaryButton_Disabled:"#585858"
    property string primaryButtonText_Disabled:"#2c2c2c"
    property string textField_Disabled:"#585858"
    property string textFieldText_Disabled:"#bfbfbf"
    property string mapButton_Disabled:"#585858"
    property string mapButtonHighlight_Disabled:"#585858"
    property string mapIndicator_Disabled:"#585858"
    property string mapIndicatorChild_Disabled:"#585858"
    property string colorGreen_Disabled:"#00e04b"
    property string colorOrange_Disabled:"#de8500"
    property string colorRed_Disabled:"#f32836"
    property string colorGrey_Disabled:"#bfbfbf"
    property string colorBlue_Disabled:"#536dff"
    property string alertBackground_Disabled:"#eecc44"
    property string alertBorder_Disabled:"#808080"
    property string alertText_Disabled:"#000000"
    property string missionItemEditor_Disabled:"#585858"
    property string mapWidgetBorderLight_Disabled:"#ffffff"
    property string mapWidgetBorderDark_Disabled:"#000000"
    property string brandingPurple_Disabled:"#4A2C6D"
    property string brandingBlue_Disabled:"#48D6FF"

    //enable
    property string window:"#444444"
    property string windowShade:"#333333"
    property string windowShadeDark:"#282828"
    property string text:"#ffffff"
    property string warningText:"#f85761"
    property string button:"#626270"
    property string buttonText:"#ffffff"
   // property string buttonHighlight:"#fff291"
   property string buttonHighlight: "#00ccff"
    property string buttonHighlightText:"#000000"
    property string primaryButton:"#8cb3be"
    property string primaryButtonText:"#000000"
    property string textField:"#ffffff"
    property string textFieldText:"#000000"
    property string mapButton:"#000000"
    property string mapButtonHighlight:"#be781c"
    property string mapIndicator:"#be781c"
    property string mapIndicatorChild:"#766043"
    property string colorGreen:"#00e04b"
    property string colorOrange:"#de8500"
    property string colorRed:"#f32836"
    property string colorGrey:"#bfbfbf"
    property string colorBlue:"#536dff"
    property string alertBackground:"#eecc44"
    property string alertBorder:"#808080"
    property string alertText:"#000000"
    property string missionItemEditor:"#8cb3be"
    property string mapWidgetBorderLight:"#ffffff"
    property string mapWidgetBorderDark:"#000000"
    property string brandingPurple:"#4A2C6D"
    property string brandingBlue:"#48D6FF"


}
